### PR TITLE
update the sample user-data for cloud

### PR DESCRIPTION
**Pull request by davidcassany**
Signed-off-by: David Cassany <dcassany@suse.com>

### CODE REVIEW

**Comment by davidcassany** [comment]
Updates docs along with rancher-sandbox/cOS-toolkit#424

I noticed this sample user-data.yaml file is copied three times in the same page of docs. I am wondering if there is a way to embed a remote yaml file into the page. So it all gets synched with `images/sampler-user-data.yaml` from the main source repository. Any idea?

**Comment by Itxaka** [comment]
yup, with https://gohugo.io/templates/partials/ we should be able to include the same piece across different pages

**Comment by Itxaka** [comment]
oh, a remote one, didnt read that :D

**Comment by davidcassany** [comment]
> oh, a remote one, didnt read that :D

well, having it duplicated only once would be already an enhancement ;)

**Comment by Itxaka** [comment]
AFAIK there is only getJson or getCSV, not getYAML -> https://gohugo.io/templates/data-templates/#get-remote-data

**Review by Itxaka — APPROVED** [review]

**Comment by mudler** [comment]
> Updates docs along with [rancher-sandbox/cOS-toolkit#424](https://github.com/rancher-sandbox/cOS-toolkit/pull/424)
> 
> I noticed this sample user-data.yaml file is copied three times in the same page of docs. I am wondering if there is a way to embed a remote yaml file into the page. So it all gets synched with `images/sampler-user-data.yaml` from the main source repository. Any idea?

Oh yes there is, I remember I crafted a special shortcode on the KubeCF docs for that purpose, I'll backport it here

**Comment by mudler** [comment]
Opened https://github.com/rancher-sandbox/cos-toolkit-docs/pull/9 to add the githubembed shortcode :+1:

**Pull request merged**
